### ISSUE TITLE
Need small adjustment on FMI map 

### ISSUE THREAD

**Issue by Ye-walmart** [Ye-walmart/Leapfrog_FMI#29]
I have been in 2800 yesterday's afternoon and I saw changes of store layout and it's aligned with the latest map shared by Pauline yesterday. Please make sure you have the right file and update the map accordingly. Changes has been highlighted in the red circles. 

[Bao'an Xin'an 5th RD_mer37_20180327.pdf](https://github.com/Ye-walmart/Leapfrog_FMI/files/1854780/Bao.an.Xin.an.5th.RD_mer37_20180327.pdf)

**Comment by xueyuanren** [comment]
Updated.

**Comment by fuzhuang** [comment]
Closing as updated.
