### ISSUE TITLE
UI-KIT Alignment

### ISSUE THREAD

**Issue by xueyuanren** [Ye-walmart/Leapfrog_FMI#35]
Here are the updated UI-kit and new color palette. Please add elements such as dialogs, tags from your side @Simon.

[UI-Kit.zip](https://github.com/Ye-walmart/Leapfrog_FMI/files/1870966/UI-Kit.zip)

![image](https://user-images.githubusercontent.com/24289621/38242023-502de524-3766-11e8-9399-65545143145a.png)

cc @fuzhuang @Ye-walmart

**Comment by fuzhuang** [comment]
@Ye-walmart currently, the only open question would be to align the UIUX for store selector. We've agreed that this feature from user perspective should be the same for both apps. So I guess we need to align a unified UIUX so both side to make the update towards the same experience.

**Comment by xueyuanren** [comment]
Updated some small changes in this version. We've added the elements from Scan and go as well.
![image](https://user-images.githubusercontent.com/24289621/38463219-16c1d640-3b28-11e8-8268-a92653ff93d3.png)

sketch file
[UI-Kit.zip](https://github.com/Ye-walmart/Leapfrog_FMI/files/1887039/UI-Kit.zip)


cc @fuzhuang @Ye-walmart

**Comment by xueyuanren** [comment]
Close as done.
